export enum MESSAGE {
  NO_SE_PUDO_ACCEDER_A_LA_URL = 'NO SE PUEDE ACCERDER A LA URL',
  BOLETO_NO_EXISTE = 'NO EXISTE',
  BOLETO_GANADOR = 'GANADOR',
  BOLETO_NO_GANADOR = 'NO GANADOR',
  BOLETO_PAGADO = 'PAGADO',
  BOLETO_ACTIVO = 'ACTIVO',
  BOLETO_CANJEADO = 'CANJEADO',
  BOLETO_CADUCADO = 'CADUCADO',
}
